//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson-jodatime-serialisers/build/mainTranslationExtraction/com/fatboyindustrial/gsonjodatime/Converters.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Converters")
#ifdef RESTRICT_Converters
#define INCLUDE_ALL_Converters 0
#else
#define INCLUDE_ALL_Converters 1
#endif
#undef RESTRICT_Converters

#if !defined (ComFatboyindustrialGsonjodatimeConverters_) && (INCLUDE_ALL_Converters || defined(INCLUDE_ComFatboyindustrialGsonjodatimeConverters))
#define ComFatboyindustrialGsonjodatimeConverters_

@class ComGoogleGsonGsonBuilder;
@protocol JavaLangReflectType;

@interface ComFatboyindustrialGsonjodatimeConverters : NSObject

#pragma mark Public

- (instancetype)init;

+ (ComGoogleGsonGsonBuilder *)registerAllWithComGoogleGsonGsonBuilder:(ComGoogleGsonGsonBuilder *)builder;

+ (ComGoogleGsonGsonBuilder *)registerDateMidnightWithComGoogleGsonGsonBuilder:(ComGoogleGsonGsonBuilder *)builder;

+ (ComGoogleGsonGsonBuilder *)registerDateTimeWithComGoogleGsonGsonBuilder:(ComGoogleGsonGsonBuilder *)builder;

+ (ComGoogleGsonGsonBuilder *)registerDurationWithComGoogleGsonGsonBuilder:(ComGoogleGsonGsonBuilder *)builder;

+ (ComGoogleGsonGsonBuilder *)registerInstantWithComGoogleGsonGsonBuilder:(ComGoogleGsonGsonBuilder *)builder;

+ (ComGoogleGsonGsonBuilder *)registerIntervalWithComGoogleGsonGsonBuilder:(ComGoogleGsonGsonBuilder *)builder;

+ (ComGoogleGsonGsonBuilder *)registerLocalDateWithComGoogleGsonGsonBuilder:(ComGoogleGsonGsonBuilder *)builder;

+ (ComGoogleGsonGsonBuilder *)registerLocalDateTimeWithComGoogleGsonGsonBuilder:(ComGoogleGsonGsonBuilder *)builder;

+ (ComGoogleGsonGsonBuilder *)registerLocalTimeWithComGoogleGsonGsonBuilder:(ComGoogleGsonGsonBuilder *)builder;

+ (ComGoogleGsonGsonBuilder *)registerPeriodWithComGoogleGsonGsonBuilder:(ComGoogleGsonGsonBuilder *)builder;

@end

J2OBJC_STATIC_INIT(ComFatboyindustrialGsonjodatimeConverters)

inline id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_get_DATE_MIDNIGHT_TYPE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_DATE_MIDNIGHT_TYPE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComFatboyindustrialGsonjodatimeConverters, DATE_MIDNIGHT_TYPE, id<JavaLangReflectType>)

inline id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_get_DATE_TIME_TYPE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_DATE_TIME_TYPE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComFatboyindustrialGsonjodatimeConverters, DATE_TIME_TYPE, id<JavaLangReflectType>)

inline id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_get_LOCAL_DATE_TYPE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_LOCAL_DATE_TYPE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComFatboyindustrialGsonjodatimeConverters, LOCAL_DATE_TYPE, id<JavaLangReflectType>)

inline id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_get_LOCAL_DATE_TIME_TYPE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_LOCAL_DATE_TIME_TYPE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComFatboyindustrialGsonjodatimeConverters, LOCAL_DATE_TIME_TYPE, id<JavaLangReflectType>)

inline id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_get_LOCAL_TIME_TYPE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_LOCAL_TIME_TYPE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComFatboyindustrialGsonjodatimeConverters, LOCAL_TIME_TYPE, id<JavaLangReflectType>)

inline id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_get_INTERVAL_TYPE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_INTERVAL_TYPE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComFatboyindustrialGsonjodatimeConverters, INTERVAL_TYPE, id<JavaLangReflectType>)

inline id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_get_DURATION_TYPE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_DURATION_TYPE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComFatboyindustrialGsonjodatimeConverters, DURATION_TYPE, id<JavaLangReflectType>)

inline id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_get_PERIOD_TYPE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_PERIOD_TYPE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComFatboyindustrialGsonjodatimeConverters, PERIOD_TYPE, id<JavaLangReflectType>)

inline id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_get_INSTANT_TYPE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_INSTANT_TYPE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComFatboyindustrialGsonjodatimeConverters, INSTANT_TYPE, id<JavaLangReflectType>)

FOUNDATION_EXPORT ComGoogleGsonGsonBuilder *ComFatboyindustrialGsonjodatimeConverters_registerAllWithComGoogleGsonGsonBuilder_(ComGoogleGsonGsonBuilder *builder);

FOUNDATION_EXPORT ComGoogleGsonGsonBuilder *ComFatboyindustrialGsonjodatimeConverters_registerDateMidnightWithComGoogleGsonGsonBuilder_(ComGoogleGsonGsonBuilder *builder);

FOUNDATION_EXPORT ComGoogleGsonGsonBuilder *ComFatboyindustrialGsonjodatimeConverters_registerDateTimeWithComGoogleGsonGsonBuilder_(ComGoogleGsonGsonBuilder *builder);

FOUNDATION_EXPORT ComGoogleGsonGsonBuilder *ComFatboyindustrialGsonjodatimeConverters_registerDurationWithComGoogleGsonGsonBuilder_(ComGoogleGsonGsonBuilder *builder);

FOUNDATION_EXPORT ComGoogleGsonGsonBuilder *ComFatboyindustrialGsonjodatimeConverters_registerLocalDateWithComGoogleGsonGsonBuilder_(ComGoogleGsonGsonBuilder *builder);

FOUNDATION_EXPORT ComGoogleGsonGsonBuilder *ComFatboyindustrialGsonjodatimeConverters_registerLocalDateTimeWithComGoogleGsonGsonBuilder_(ComGoogleGsonGsonBuilder *builder);

FOUNDATION_EXPORT ComGoogleGsonGsonBuilder *ComFatboyindustrialGsonjodatimeConverters_registerLocalTimeWithComGoogleGsonGsonBuilder_(ComGoogleGsonGsonBuilder *builder);

FOUNDATION_EXPORT ComGoogleGsonGsonBuilder *ComFatboyindustrialGsonjodatimeConverters_registerInstantWithComGoogleGsonGsonBuilder_(ComGoogleGsonGsonBuilder *builder);

FOUNDATION_EXPORT ComGoogleGsonGsonBuilder *ComFatboyindustrialGsonjodatimeConverters_registerIntervalWithComGoogleGsonGsonBuilder_(ComGoogleGsonGsonBuilder *builder);

FOUNDATION_EXPORT ComGoogleGsonGsonBuilder *ComFatboyindustrialGsonjodatimeConverters_registerPeriodWithComGoogleGsonGsonBuilder_(ComGoogleGsonGsonBuilder *builder);

FOUNDATION_EXPORT void ComFatboyindustrialGsonjodatimeConverters_init(ComFatboyindustrialGsonjodatimeConverters *self);

FOUNDATION_EXPORT ComFatboyindustrialGsonjodatimeConverters *new_ComFatboyindustrialGsonjodatimeConverters_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComFatboyindustrialGsonjodatimeConverters *create_ComFatboyindustrialGsonjodatimeConverters_init();

J2OBJC_TYPE_LITERAL_HEADER(ComFatboyindustrialGsonjodatimeConverters)

#endif

#pragma pop_macro("INCLUDE_ALL_Converters")
