//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson-jodatime-serialisers/build/mainTranslationExtraction/com/fatboyindustrial/gsonjodatime/Converters.java
//

#include "Converters.h"
#include "DateMidnightConverter.h"
#include "DateTimeConverter.h"
#include "DurationConverter.h"
#include "GsonBuilder.h"
#include "InstantConverter.h"
#include "IntervalConverter.h"
#include "J2ObjC_source.h"
#include "LocalDateConverter.h"
#include "LocalDateTimeConverter.h"
#include "LocalTimeConverter.h"
#include "PeriodConverter.h"
#include "TypeToken.h"
#include "java/lang/NullPointerException.h"
#include "java/lang/reflect/Type.h"

@interface ComFatboyindustrialGsonjodatimeConverters_$1 : ComGoogleGsonReflectTypeToken

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFatboyindustrialGsonjodatimeConverters_$1)

__attribute__((unused)) static void ComFatboyindustrialGsonjodatimeConverters_$1_init(ComFatboyindustrialGsonjodatimeConverters_$1 *self);

__attribute__((unused)) static ComFatboyindustrialGsonjodatimeConverters_$1 *new_ComFatboyindustrialGsonjodatimeConverters_$1_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComFatboyindustrialGsonjodatimeConverters_$1 *create_ComFatboyindustrialGsonjodatimeConverters_$1_init();

@interface ComFatboyindustrialGsonjodatimeConverters_$2 : ComGoogleGsonReflectTypeToken

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFatboyindustrialGsonjodatimeConverters_$2)

__attribute__((unused)) static void ComFatboyindustrialGsonjodatimeConverters_$2_init(ComFatboyindustrialGsonjodatimeConverters_$2 *self);

__attribute__((unused)) static ComFatboyindustrialGsonjodatimeConverters_$2 *new_ComFatboyindustrialGsonjodatimeConverters_$2_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComFatboyindustrialGsonjodatimeConverters_$2 *create_ComFatboyindustrialGsonjodatimeConverters_$2_init();

@interface ComFatboyindustrialGsonjodatimeConverters_$3 : ComGoogleGsonReflectTypeToken

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFatboyindustrialGsonjodatimeConverters_$3)

__attribute__((unused)) static void ComFatboyindustrialGsonjodatimeConverters_$3_init(ComFatboyindustrialGsonjodatimeConverters_$3 *self);

__attribute__((unused)) static ComFatboyindustrialGsonjodatimeConverters_$3 *new_ComFatboyindustrialGsonjodatimeConverters_$3_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComFatboyindustrialGsonjodatimeConverters_$3 *create_ComFatboyindustrialGsonjodatimeConverters_$3_init();

@interface ComFatboyindustrialGsonjodatimeConverters_$4 : ComGoogleGsonReflectTypeToken

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFatboyindustrialGsonjodatimeConverters_$4)

__attribute__((unused)) static void ComFatboyindustrialGsonjodatimeConverters_$4_init(ComFatboyindustrialGsonjodatimeConverters_$4 *self);

__attribute__((unused)) static ComFatboyindustrialGsonjodatimeConverters_$4 *new_ComFatboyindustrialGsonjodatimeConverters_$4_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComFatboyindustrialGsonjodatimeConverters_$4 *create_ComFatboyindustrialGsonjodatimeConverters_$4_init();

@interface ComFatboyindustrialGsonjodatimeConverters_$5 : ComGoogleGsonReflectTypeToken

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFatboyindustrialGsonjodatimeConverters_$5)

__attribute__((unused)) static void ComFatboyindustrialGsonjodatimeConverters_$5_init(ComFatboyindustrialGsonjodatimeConverters_$5 *self);

__attribute__((unused)) static ComFatboyindustrialGsonjodatimeConverters_$5 *new_ComFatboyindustrialGsonjodatimeConverters_$5_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComFatboyindustrialGsonjodatimeConverters_$5 *create_ComFatboyindustrialGsonjodatimeConverters_$5_init();

@interface ComFatboyindustrialGsonjodatimeConverters_$6 : ComGoogleGsonReflectTypeToken

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFatboyindustrialGsonjodatimeConverters_$6)

__attribute__((unused)) static void ComFatboyindustrialGsonjodatimeConverters_$6_init(ComFatboyindustrialGsonjodatimeConverters_$6 *self);

__attribute__((unused)) static ComFatboyindustrialGsonjodatimeConverters_$6 *new_ComFatboyindustrialGsonjodatimeConverters_$6_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComFatboyindustrialGsonjodatimeConverters_$6 *create_ComFatboyindustrialGsonjodatimeConverters_$6_init();

@interface ComFatboyindustrialGsonjodatimeConverters_$7 : ComGoogleGsonReflectTypeToken

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFatboyindustrialGsonjodatimeConverters_$7)

__attribute__((unused)) static void ComFatboyindustrialGsonjodatimeConverters_$7_init(ComFatboyindustrialGsonjodatimeConverters_$7 *self);

__attribute__((unused)) static ComFatboyindustrialGsonjodatimeConverters_$7 *new_ComFatboyindustrialGsonjodatimeConverters_$7_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComFatboyindustrialGsonjodatimeConverters_$7 *create_ComFatboyindustrialGsonjodatimeConverters_$7_init();

@interface ComFatboyindustrialGsonjodatimeConverters_$8 : ComGoogleGsonReflectTypeToken

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFatboyindustrialGsonjodatimeConverters_$8)

__attribute__((unused)) static void ComFatboyindustrialGsonjodatimeConverters_$8_init(ComFatboyindustrialGsonjodatimeConverters_$8 *self);

__attribute__((unused)) static ComFatboyindustrialGsonjodatimeConverters_$8 *new_ComFatboyindustrialGsonjodatimeConverters_$8_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComFatboyindustrialGsonjodatimeConverters_$8 *create_ComFatboyindustrialGsonjodatimeConverters_$8_init();

@interface ComFatboyindustrialGsonjodatimeConverters_$9 : ComGoogleGsonReflectTypeToken

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFatboyindustrialGsonjodatimeConverters_$9)

__attribute__((unused)) static void ComFatboyindustrialGsonjodatimeConverters_$9_init(ComFatboyindustrialGsonjodatimeConverters_$9 *self);

__attribute__((unused)) static ComFatboyindustrialGsonjodatimeConverters_$9 *new_ComFatboyindustrialGsonjodatimeConverters_$9_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComFatboyindustrialGsonjodatimeConverters_$9 *create_ComFatboyindustrialGsonjodatimeConverters_$9_init();

J2OBJC_INITIALIZED_DEFN(ComFatboyindustrialGsonjodatimeConverters)

id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_DATE_MIDNIGHT_TYPE;
id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_DATE_TIME_TYPE;
id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_LOCAL_DATE_TYPE;
id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_LOCAL_DATE_TIME_TYPE;
id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_LOCAL_TIME_TYPE;
id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_INTERVAL_TYPE;
id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_DURATION_TYPE;
id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_PERIOD_TYPE;
id<JavaLangReflectType> ComFatboyindustrialGsonjodatimeConverters_INSTANT_TYPE;

@implementation ComFatboyindustrialGsonjodatimeConverters

+ (ComGoogleGsonGsonBuilder *)registerAllWithComGoogleGsonGsonBuilder:(ComGoogleGsonGsonBuilder *)builder {
  return ComFatboyindustrialGsonjodatimeConverters_registerAllWithComGoogleGsonGsonBuilder_(builder);
}

+ (ComGoogleGsonGsonBuilder *)registerDateMidnightWithComGoogleGsonGsonBuilder:(ComGoogleGsonGsonBuilder *)builder {
  return ComFatboyindustrialGsonjodatimeConverters_registerDateMidnightWithComGoogleGsonGsonBuilder_(builder);
}

+ (ComGoogleGsonGsonBuilder *)registerDateTimeWithComGoogleGsonGsonBuilder:(ComGoogleGsonGsonBuilder *)builder {
  return ComFatboyindustrialGsonjodatimeConverters_registerDateTimeWithComGoogleGsonGsonBuilder_(builder);
}

+ (ComGoogleGsonGsonBuilder *)registerDurationWithComGoogleGsonGsonBuilder:(ComGoogleGsonGsonBuilder *)builder {
  return ComFatboyindustrialGsonjodatimeConverters_registerDurationWithComGoogleGsonGsonBuilder_(builder);
}

+ (ComGoogleGsonGsonBuilder *)registerLocalDateWithComGoogleGsonGsonBuilder:(ComGoogleGsonGsonBuilder *)builder {
  return ComFatboyindustrialGsonjodatimeConverters_registerLocalDateWithComGoogleGsonGsonBuilder_(builder);
}

+ (ComGoogleGsonGsonBuilder *)registerLocalDateTimeWithComGoogleGsonGsonBuilder:(ComGoogleGsonGsonBuilder *)builder {
  return ComFatboyindustrialGsonjodatimeConverters_registerLocalDateTimeWithComGoogleGsonGsonBuilder_(builder);
}

+ (ComGoogleGsonGsonBuilder *)registerLocalTimeWithComGoogleGsonGsonBuilder:(ComGoogleGsonGsonBuilder *)builder {
  return ComFatboyindustrialGsonjodatimeConverters_registerLocalTimeWithComGoogleGsonGsonBuilder_(builder);
}

+ (ComGoogleGsonGsonBuilder *)registerInstantWithComGoogleGsonGsonBuilder:(ComGoogleGsonGsonBuilder *)builder {
  return ComFatboyindustrialGsonjodatimeConverters_registerInstantWithComGoogleGsonGsonBuilder_(builder);
}

+ (ComGoogleGsonGsonBuilder *)registerIntervalWithComGoogleGsonGsonBuilder:(ComGoogleGsonGsonBuilder *)builder {
  return ComFatboyindustrialGsonjodatimeConverters_registerIntervalWithComGoogleGsonGsonBuilder_(builder);
}

+ (ComGoogleGsonGsonBuilder *)registerPeriodWithComGoogleGsonGsonBuilder:(ComGoogleGsonGsonBuilder *)builder {
  return ComFatboyindustrialGsonjodatimeConverters_registerPeriodWithComGoogleGsonGsonBuilder_(builder);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComFatboyindustrialGsonjodatimeConverters_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LComGoogleGsonGsonBuilder;", 0x9, 0, 1, -1, -1, -1, -1 },
    { NULL, "LComGoogleGsonGsonBuilder;", 0x9, 2, 1, -1, -1, -1, -1 },
    { NULL, "LComGoogleGsonGsonBuilder;", 0x9, 3, 1, -1, -1, -1, -1 },
    { NULL, "LComGoogleGsonGsonBuilder;", 0x9, 4, 1, -1, -1, -1, -1 },
    { NULL, "LComGoogleGsonGsonBuilder;", 0x9, 5, 1, -1, -1, -1, -1 },
    { NULL, "LComGoogleGsonGsonBuilder;", 0x9, 6, 1, -1, -1, -1, -1 },
    { NULL, "LComGoogleGsonGsonBuilder;", 0x9, 7, 1, -1, -1, -1, -1 },
    { NULL, "LComGoogleGsonGsonBuilder;", 0x9, 8, 1, -1, -1, -1, -1 },
    { NULL, "LComGoogleGsonGsonBuilder;", 0x9, 9, 1, -1, -1, -1, -1 },
    { NULL, "LComGoogleGsonGsonBuilder;", 0x9, 10, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(registerAllWithComGoogleGsonGsonBuilder:);
  methods[1].selector = @selector(registerDateMidnightWithComGoogleGsonGsonBuilder:);
  methods[2].selector = @selector(registerDateTimeWithComGoogleGsonGsonBuilder:);
  methods[3].selector = @selector(registerDurationWithComGoogleGsonGsonBuilder:);
  methods[4].selector = @selector(registerLocalDateWithComGoogleGsonGsonBuilder:);
  methods[5].selector = @selector(registerLocalDateTimeWithComGoogleGsonGsonBuilder:);
  methods[6].selector = @selector(registerLocalTimeWithComGoogleGsonGsonBuilder:);
  methods[7].selector = @selector(registerInstantWithComGoogleGsonGsonBuilder:);
  methods[8].selector = @selector(registerIntervalWithComGoogleGsonGsonBuilder:);
  methods[9].selector = @selector(registerPeriodWithComGoogleGsonGsonBuilder:);
  methods[10].selector = @selector(init);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "DATE_MIDNIGHT_TYPE", "LJavaLangReflectType;", .constantValue.asLong = 0, 0x19, -1, 11, -1, -1 },
    { "DATE_TIME_TYPE", "LJavaLangReflectType;", .constantValue.asLong = 0, 0x19, -1, 12, -1, -1 },
    { "LOCAL_DATE_TYPE", "LJavaLangReflectType;", .constantValue.asLong = 0, 0x19, -1, 13, -1, -1 },
    { "LOCAL_DATE_TIME_TYPE", "LJavaLangReflectType;", .constantValue.asLong = 0, 0x19, -1, 14, -1, -1 },
    { "LOCAL_TIME_TYPE", "LJavaLangReflectType;", .constantValue.asLong = 0, 0x19, -1, 15, -1, -1 },
    { "INTERVAL_TYPE", "LJavaLangReflectType;", .constantValue.asLong = 0, 0x19, -1, 16, -1, -1 },
    { "DURATION_TYPE", "LJavaLangReflectType;", .constantValue.asLong = 0, 0x19, -1, 17, -1, -1 },
    { "PERIOD_TYPE", "LJavaLangReflectType;", .constantValue.asLong = 0, 0x19, -1, 18, -1, -1 },
    { "INSTANT_TYPE", "LJavaLangReflectType;", .constantValue.asLong = 0, 0x19, -1, 19, -1, -1 },
  };
  static const void *ptrTable[] = { "registerAll", "LComGoogleGsonGsonBuilder;", "registerDateMidnight", "registerDateTime", "registerDuration", "registerLocalDate", "registerLocalDateTime", "registerLocalTime", "registerInstant", "registerInterval", "registerPeriod", &ComFatboyindustrialGsonjodatimeConverters_DATE_MIDNIGHT_TYPE, &ComFatboyindustrialGsonjodatimeConverters_DATE_TIME_TYPE, &ComFatboyindustrialGsonjodatimeConverters_LOCAL_DATE_TYPE, &ComFatboyindustrialGsonjodatimeConverters_LOCAL_DATE_TIME_TYPE, &ComFatboyindustrialGsonjodatimeConverters_LOCAL_TIME_TYPE, &ComFatboyindustrialGsonjodatimeConverters_INTERVAL_TYPE, &ComFatboyindustrialGsonjodatimeConverters_DURATION_TYPE, &ComFatboyindustrialGsonjodatimeConverters_PERIOD_TYPE, &ComFatboyindustrialGsonjodatimeConverters_INSTANT_TYPE };
  static const J2ObjcClassInfo _ComFatboyindustrialGsonjodatimeConverters = { "Converters", "com.fatboyindustrial.gsonjodatime", ptrTable, methods, fields, 7, 0x1, 11, 9, -1, -1, -1, -1, -1 };
  return &_ComFatboyindustrialGsonjodatimeConverters;
}

+ (void)initialize {
  if (self == [ComFatboyindustrialGsonjodatimeConverters class]) {
    ComFatboyindustrialGsonjodatimeConverters_DATE_MIDNIGHT_TYPE = [new_ComFatboyindustrialGsonjodatimeConverters_$1_init() getType];
    ComFatboyindustrialGsonjodatimeConverters_DATE_TIME_TYPE = [new_ComFatboyindustrialGsonjodatimeConverters_$2_init() getType];
    ComFatboyindustrialGsonjodatimeConverters_LOCAL_DATE_TYPE = [new_ComFatboyindustrialGsonjodatimeConverters_$3_init() getType];
    ComFatboyindustrialGsonjodatimeConverters_LOCAL_DATE_TIME_TYPE = [new_ComFatboyindustrialGsonjodatimeConverters_$4_init() getType];
    ComFatboyindustrialGsonjodatimeConverters_LOCAL_TIME_TYPE = [new_ComFatboyindustrialGsonjodatimeConverters_$5_init() getType];
    ComFatboyindustrialGsonjodatimeConverters_INTERVAL_TYPE = [new_ComFatboyindustrialGsonjodatimeConverters_$6_init() getType];
    ComFatboyindustrialGsonjodatimeConverters_DURATION_TYPE = [new_ComFatboyindustrialGsonjodatimeConverters_$7_init() getType];
    ComFatboyindustrialGsonjodatimeConverters_PERIOD_TYPE = [new_ComFatboyindustrialGsonjodatimeConverters_$8_init() getType];
    ComFatboyindustrialGsonjodatimeConverters_INSTANT_TYPE = [new_ComFatboyindustrialGsonjodatimeConverters_$9_init() getType];
    J2OBJC_SET_INITIALIZED(ComFatboyindustrialGsonjodatimeConverters)
  }
}

@end

ComGoogleGsonGsonBuilder *ComFatboyindustrialGsonjodatimeConverters_registerAllWithComGoogleGsonGsonBuilder_(ComGoogleGsonGsonBuilder *builder) {
  ComFatboyindustrialGsonjodatimeConverters_initialize();
  if (builder == nil) {
    @throw new_JavaLangNullPointerException_initWithNSString_(@"builder cannot be null");
  }
  (void) ComFatboyindustrialGsonjodatimeConverters_registerDateMidnightWithComGoogleGsonGsonBuilder_(builder);
  (void) ComFatboyindustrialGsonjodatimeConverters_registerDateTimeWithComGoogleGsonGsonBuilder_(builder);
  (void) ComFatboyindustrialGsonjodatimeConverters_registerDurationWithComGoogleGsonGsonBuilder_(builder);
  (void) ComFatboyindustrialGsonjodatimeConverters_registerLocalDateWithComGoogleGsonGsonBuilder_(builder);
  (void) ComFatboyindustrialGsonjodatimeConverters_registerLocalDateTimeWithComGoogleGsonGsonBuilder_(builder);
  (void) ComFatboyindustrialGsonjodatimeConverters_registerLocalTimeWithComGoogleGsonGsonBuilder_(builder);
  (void) ComFatboyindustrialGsonjodatimeConverters_registerIntervalWithComGoogleGsonGsonBuilder_(builder);
  (void) ComFatboyindustrialGsonjodatimeConverters_registerPeriodWithComGoogleGsonGsonBuilder_(builder);
  (void) ComFatboyindustrialGsonjodatimeConverters_registerInstantWithComGoogleGsonGsonBuilder_(builder);
  return builder;
}

ComGoogleGsonGsonBuilder *ComFatboyindustrialGsonjodatimeConverters_registerDateMidnightWithComGoogleGsonGsonBuilder_(ComGoogleGsonGsonBuilder *builder) {
  ComFatboyindustrialGsonjodatimeConverters_initialize();
  if (builder == nil) {
    @throw new_JavaLangNullPointerException_initWithNSString_(@"builder cannot be null");
  }
  (void) [builder registerTypeAdapterWithJavaLangReflectType:ComFatboyindustrialGsonjodatimeConverters_DATE_MIDNIGHT_TYPE withId:new_ComFatboyindustrialGsonjodatimeDateMidnightConverter_init()];
  return builder;
}

ComGoogleGsonGsonBuilder *ComFatboyindustrialGsonjodatimeConverters_registerDateTimeWithComGoogleGsonGsonBuilder_(ComGoogleGsonGsonBuilder *builder) {
  ComFatboyindustrialGsonjodatimeConverters_initialize();
  if (builder == nil) {
    @throw new_JavaLangNullPointerException_initWithNSString_(@"builder cannot be null");
  }
  (void) [builder registerTypeAdapterWithJavaLangReflectType:ComFatboyindustrialGsonjodatimeConverters_DATE_TIME_TYPE withId:new_ComFatboyindustrialGsonjodatimeDateTimeConverter_init()];
  return builder;
}

ComGoogleGsonGsonBuilder *ComFatboyindustrialGsonjodatimeConverters_registerDurationWithComGoogleGsonGsonBuilder_(ComGoogleGsonGsonBuilder *builder) {
  ComFatboyindustrialGsonjodatimeConverters_initialize();
  if (builder == nil) {
    @throw new_JavaLangNullPointerException_initWithNSString_(@"builder cannot be null");
  }
  (void) [builder registerTypeAdapterWithJavaLangReflectType:ComFatboyindustrialGsonjodatimeConverters_DURATION_TYPE withId:new_ComFatboyindustrialGsonjodatimeDurationConverter_init()];
  return builder;
}

ComGoogleGsonGsonBuilder *ComFatboyindustrialGsonjodatimeConverters_registerLocalDateWithComGoogleGsonGsonBuilder_(ComGoogleGsonGsonBuilder *builder) {
  ComFatboyindustrialGsonjodatimeConverters_initialize();
  if (builder == nil) {
    @throw new_JavaLangNullPointerException_initWithNSString_(@"builder cannot be null");
  }
  (void) [builder registerTypeAdapterWithJavaLangReflectType:ComFatboyindustrialGsonjodatimeConverters_LOCAL_DATE_TYPE withId:new_ComFatboyindustrialGsonjodatimeLocalDateConverter_init()];
  return builder;
}

ComGoogleGsonGsonBuilder *ComFatboyindustrialGsonjodatimeConverters_registerLocalDateTimeWithComGoogleGsonGsonBuilder_(ComGoogleGsonGsonBuilder *builder) {
  ComFatboyindustrialGsonjodatimeConverters_initialize();
  if (builder == nil) {
    @throw new_JavaLangNullPointerException_initWithNSString_(@"builder cannot be null");
  }
  (void) [builder registerTypeAdapterWithJavaLangReflectType:ComFatboyindustrialGsonjodatimeConverters_LOCAL_DATE_TIME_TYPE withId:new_ComFatboyindustrialGsonjodatimeLocalDateTimeConverter_init()];
  return builder;
}

ComGoogleGsonGsonBuilder *ComFatboyindustrialGsonjodatimeConverters_registerLocalTimeWithComGoogleGsonGsonBuilder_(ComGoogleGsonGsonBuilder *builder) {
  ComFatboyindustrialGsonjodatimeConverters_initialize();
  if (builder == nil) {
    @throw new_JavaLangNullPointerException_initWithNSString_(@"builder cannot be null");
  }
  (void) [builder registerTypeAdapterWithJavaLangReflectType:ComFatboyindustrialGsonjodatimeConverters_LOCAL_TIME_TYPE withId:new_ComFatboyindustrialGsonjodatimeLocalTimeConverter_init()];
  return builder;
}

ComGoogleGsonGsonBuilder *ComFatboyindustrialGsonjodatimeConverters_registerInstantWithComGoogleGsonGsonBuilder_(ComGoogleGsonGsonBuilder *builder) {
  ComFatboyindustrialGsonjodatimeConverters_initialize();
  if (builder == nil) {
    @throw new_JavaLangNullPointerException_initWithNSString_(@"builder cannot be null");
  }
  (void) [builder registerTypeAdapterWithJavaLangReflectType:ComFatboyindustrialGsonjodatimeConverters_INSTANT_TYPE withId:new_ComFatboyindustrialGsonjodatimeInstantConverter_init()];
  return builder;
}

ComGoogleGsonGsonBuilder *ComFatboyindustrialGsonjodatimeConverters_registerIntervalWithComGoogleGsonGsonBuilder_(ComGoogleGsonGsonBuilder *builder) {
  ComFatboyindustrialGsonjodatimeConverters_initialize();
  if (builder == nil) {
    @throw new_JavaLangNullPointerException_initWithNSString_(@"builder cannot be null");
  }
  (void) [builder registerTypeAdapterWithJavaLangReflectType:ComFatboyindustrialGsonjodatimeConverters_INTERVAL_TYPE withId:new_ComFatboyindustrialGsonjodatimeIntervalConverter_init()];
  return builder;
}

ComGoogleGsonGsonBuilder *ComFatboyindustrialGsonjodatimeConverters_registerPeriodWithComGoogleGsonGsonBuilder_(ComGoogleGsonGsonBuilder *builder) {
  ComFatboyindustrialGsonjodatimeConverters_initialize();
  if (builder == nil) {
    @throw new_JavaLangNullPointerException_initWithNSString_(@"builder cannot be null");
  }
  (void) [builder registerTypeAdapterWithJavaLangReflectType:ComFatboyindustrialGsonjodatimeConverters_PERIOD_TYPE withId:new_ComFatboyindustrialGsonjodatimePeriodConverter_init()];
  return builder;
}

void ComFatboyindustrialGsonjodatimeConverters_init(ComFatboyindustrialGsonjodatimeConverters *self) {
  NSObject_init(self);
}

ComFatboyindustrialGsonjodatimeConverters *new_ComFatboyindustrialGsonjodatimeConverters_init() {
  J2OBJC_NEW_IMPL(ComFatboyindustrialGsonjodatimeConverters, init)
}

ComFatboyindustrialGsonjodatimeConverters *create_ComFatboyindustrialGsonjodatimeConverters_init() {
  J2OBJC_CREATE_IMPL(ComFatboyindustrialGsonjodatimeConverters, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComFatboyindustrialGsonjodatimeConverters)

@implementation ComFatboyindustrialGsonjodatimeConverters_$1

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComFatboyindustrialGsonjodatimeConverters_$1_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComFatboyindustrialGsonjodatimeConverters;", "Lcom/google/gson/reflect/TypeToken<Lorg/joda/time/DateMidnight;>;" };
  static const J2ObjcClassInfo _ComFatboyindustrialGsonjodatimeConverters_$1 = { "", "com.fatboyindustrial.gsonjodatime", ptrTable, methods, NULL, 7, 0x8008, 1, 0, 0, -1, -1, 1, -1 };
  return &_ComFatboyindustrialGsonjodatimeConverters_$1;
}

@end

void ComFatboyindustrialGsonjodatimeConverters_$1_init(ComFatboyindustrialGsonjodatimeConverters_$1 *self) {
  ComGoogleGsonReflectTypeToken_init(self);
}

ComFatboyindustrialGsonjodatimeConverters_$1 *new_ComFatboyindustrialGsonjodatimeConverters_$1_init() {
  J2OBJC_NEW_IMPL(ComFatboyindustrialGsonjodatimeConverters_$1, init)
}

ComFatboyindustrialGsonjodatimeConverters_$1 *create_ComFatboyindustrialGsonjodatimeConverters_$1_init() {
  J2OBJC_CREATE_IMPL(ComFatboyindustrialGsonjodatimeConverters_$1, init)
}

@implementation ComFatboyindustrialGsonjodatimeConverters_$2

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComFatboyindustrialGsonjodatimeConverters_$2_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComFatboyindustrialGsonjodatimeConverters;", "Lcom/google/gson/reflect/TypeToken<Lorg/joda/time/DateTime;>;" };
  static const J2ObjcClassInfo _ComFatboyindustrialGsonjodatimeConverters_$2 = { "", "com.fatboyindustrial.gsonjodatime", ptrTable, methods, NULL, 7, 0x8008, 1, 0, 0, -1, -1, 1, -1 };
  return &_ComFatboyindustrialGsonjodatimeConverters_$2;
}

@end

void ComFatboyindustrialGsonjodatimeConverters_$2_init(ComFatboyindustrialGsonjodatimeConverters_$2 *self) {
  ComGoogleGsonReflectTypeToken_init(self);
}

ComFatboyindustrialGsonjodatimeConverters_$2 *new_ComFatboyindustrialGsonjodatimeConverters_$2_init() {
  J2OBJC_NEW_IMPL(ComFatboyindustrialGsonjodatimeConverters_$2, init)
}

ComFatboyindustrialGsonjodatimeConverters_$2 *create_ComFatboyindustrialGsonjodatimeConverters_$2_init() {
  J2OBJC_CREATE_IMPL(ComFatboyindustrialGsonjodatimeConverters_$2, init)
}

@implementation ComFatboyindustrialGsonjodatimeConverters_$3

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComFatboyindustrialGsonjodatimeConverters_$3_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComFatboyindustrialGsonjodatimeConverters;", "Lcom/google/gson/reflect/TypeToken<Lorg/joda/time/LocalDate;>;" };
  static const J2ObjcClassInfo _ComFatboyindustrialGsonjodatimeConverters_$3 = { "", "com.fatboyindustrial.gsonjodatime", ptrTable, methods, NULL, 7, 0x8008, 1, 0, 0, -1, -1, 1, -1 };
  return &_ComFatboyindustrialGsonjodatimeConverters_$3;
}

@end

void ComFatboyindustrialGsonjodatimeConverters_$3_init(ComFatboyindustrialGsonjodatimeConverters_$3 *self) {
  ComGoogleGsonReflectTypeToken_init(self);
}

ComFatboyindustrialGsonjodatimeConverters_$3 *new_ComFatboyindustrialGsonjodatimeConverters_$3_init() {
  J2OBJC_NEW_IMPL(ComFatboyindustrialGsonjodatimeConverters_$3, init)
}

ComFatboyindustrialGsonjodatimeConverters_$3 *create_ComFatboyindustrialGsonjodatimeConverters_$3_init() {
  J2OBJC_CREATE_IMPL(ComFatboyindustrialGsonjodatimeConverters_$3, init)
}

@implementation ComFatboyindustrialGsonjodatimeConverters_$4

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComFatboyindustrialGsonjodatimeConverters_$4_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComFatboyindustrialGsonjodatimeConverters;", "Lcom/google/gson/reflect/TypeToken<Lorg/joda/time/LocalDateTime;>;" };
  static const J2ObjcClassInfo _ComFatboyindustrialGsonjodatimeConverters_$4 = { "", "com.fatboyindustrial.gsonjodatime", ptrTable, methods, NULL, 7, 0x8008, 1, 0, 0, -1, -1, 1, -1 };
  return &_ComFatboyindustrialGsonjodatimeConverters_$4;
}

@end

void ComFatboyindustrialGsonjodatimeConverters_$4_init(ComFatboyindustrialGsonjodatimeConverters_$4 *self) {
  ComGoogleGsonReflectTypeToken_init(self);
}

ComFatboyindustrialGsonjodatimeConverters_$4 *new_ComFatboyindustrialGsonjodatimeConverters_$4_init() {
  J2OBJC_NEW_IMPL(ComFatboyindustrialGsonjodatimeConverters_$4, init)
}

ComFatboyindustrialGsonjodatimeConverters_$4 *create_ComFatboyindustrialGsonjodatimeConverters_$4_init() {
  J2OBJC_CREATE_IMPL(ComFatboyindustrialGsonjodatimeConverters_$4, init)
}

@implementation ComFatboyindustrialGsonjodatimeConverters_$5

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComFatboyindustrialGsonjodatimeConverters_$5_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComFatboyindustrialGsonjodatimeConverters;", "Lcom/google/gson/reflect/TypeToken<Lorg/joda/time/LocalTime;>;" };
  static const J2ObjcClassInfo _ComFatboyindustrialGsonjodatimeConverters_$5 = { "", "com.fatboyindustrial.gsonjodatime", ptrTable, methods, NULL, 7, 0x8008, 1, 0, 0, -1, -1, 1, -1 };
  return &_ComFatboyindustrialGsonjodatimeConverters_$5;
}

@end

void ComFatboyindustrialGsonjodatimeConverters_$5_init(ComFatboyindustrialGsonjodatimeConverters_$5 *self) {
  ComGoogleGsonReflectTypeToken_init(self);
}

ComFatboyindustrialGsonjodatimeConverters_$5 *new_ComFatboyindustrialGsonjodatimeConverters_$5_init() {
  J2OBJC_NEW_IMPL(ComFatboyindustrialGsonjodatimeConverters_$5, init)
}

ComFatboyindustrialGsonjodatimeConverters_$5 *create_ComFatboyindustrialGsonjodatimeConverters_$5_init() {
  J2OBJC_CREATE_IMPL(ComFatboyindustrialGsonjodatimeConverters_$5, init)
}

@implementation ComFatboyindustrialGsonjodatimeConverters_$6

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComFatboyindustrialGsonjodatimeConverters_$6_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComFatboyindustrialGsonjodatimeConverters;", "Lcom/google/gson/reflect/TypeToken<Lorg/joda/time/Interval;>;" };
  static const J2ObjcClassInfo _ComFatboyindustrialGsonjodatimeConverters_$6 = { "", "com.fatboyindustrial.gsonjodatime", ptrTable, methods, NULL, 7, 0x8008, 1, 0, 0, -1, -1, 1, -1 };
  return &_ComFatboyindustrialGsonjodatimeConverters_$6;
}

@end

void ComFatboyindustrialGsonjodatimeConverters_$6_init(ComFatboyindustrialGsonjodatimeConverters_$6 *self) {
  ComGoogleGsonReflectTypeToken_init(self);
}

ComFatboyindustrialGsonjodatimeConverters_$6 *new_ComFatboyindustrialGsonjodatimeConverters_$6_init() {
  J2OBJC_NEW_IMPL(ComFatboyindustrialGsonjodatimeConverters_$6, init)
}

ComFatboyindustrialGsonjodatimeConverters_$6 *create_ComFatboyindustrialGsonjodatimeConverters_$6_init() {
  J2OBJC_CREATE_IMPL(ComFatboyindustrialGsonjodatimeConverters_$6, init)
}

@implementation ComFatboyindustrialGsonjodatimeConverters_$7

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComFatboyindustrialGsonjodatimeConverters_$7_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComFatboyindustrialGsonjodatimeConverters;", "Lcom/google/gson/reflect/TypeToken<Lorg/joda/time/Duration;>;" };
  static const J2ObjcClassInfo _ComFatboyindustrialGsonjodatimeConverters_$7 = { "", "com.fatboyindustrial.gsonjodatime", ptrTable, methods, NULL, 7, 0x8008, 1, 0, 0, -1, -1, 1, -1 };
  return &_ComFatboyindustrialGsonjodatimeConverters_$7;
}

@end

void ComFatboyindustrialGsonjodatimeConverters_$7_init(ComFatboyindustrialGsonjodatimeConverters_$7 *self) {
  ComGoogleGsonReflectTypeToken_init(self);
}

ComFatboyindustrialGsonjodatimeConverters_$7 *new_ComFatboyindustrialGsonjodatimeConverters_$7_init() {
  J2OBJC_NEW_IMPL(ComFatboyindustrialGsonjodatimeConverters_$7, init)
}

ComFatboyindustrialGsonjodatimeConverters_$7 *create_ComFatboyindustrialGsonjodatimeConverters_$7_init() {
  J2OBJC_CREATE_IMPL(ComFatboyindustrialGsonjodatimeConverters_$7, init)
}

@implementation ComFatboyindustrialGsonjodatimeConverters_$8

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComFatboyindustrialGsonjodatimeConverters_$8_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComFatboyindustrialGsonjodatimeConverters;", "Lcom/google/gson/reflect/TypeToken<Lorg/joda/time/Period;>;" };
  static const J2ObjcClassInfo _ComFatboyindustrialGsonjodatimeConverters_$8 = { "", "com.fatboyindustrial.gsonjodatime", ptrTable, methods, NULL, 7, 0x8008, 1, 0, 0, -1, -1, 1, -1 };
  return &_ComFatboyindustrialGsonjodatimeConverters_$8;
}

@end

void ComFatboyindustrialGsonjodatimeConverters_$8_init(ComFatboyindustrialGsonjodatimeConverters_$8 *self) {
  ComGoogleGsonReflectTypeToken_init(self);
}

ComFatboyindustrialGsonjodatimeConverters_$8 *new_ComFatboyindustrialGsonjodatimeConverters_$8_init() {
  J2OBJC_NEW_IMPL(ComFatboyindustrialGsonjodatimeConverters_$8, init)
}

ComFatboyindustrialGsonjodatimeConverters_$8 *create_ComFatboyindustrialGsonjodatimeConverters_$8_init() {
  J2OBJC_CREATE_IMPL(ComFatboyindustrialGsonjodatimeConverters_$8, init)
}

@implementation ComFatboyindustrialGsonjodatimeConverters_$9

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComFatboyindustrialGsonjodatimeConverters_$9_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComFatboyindustrialGsonjodatimeConverters;", "Lcom/google/gson/reflect/TypeToken<Lorg/joda/time/Instant;>;" };
  static const J2ObjcClassInfo _ComFatboyindustrialGsonjodatimeConverters_$9 = { "", "com.fatboyindustrial.gsonjodatime", ptrTable, methods, NULL, 7, 0x8008, 1, 0, 0, -1, -1, 1, -1 };
  return &_ComFatboyindustrialGsonjodatimeConverters_$9;
}

@end

void ComFatboyindustrialGsonjodatimeConverters_$9_init(ComFatboyindustrialGsonjodatimeConverters_$9 *self) {
  ComGoogleGsonReflectTypeToken_init(self);
}

ComFatboyindustrialGsonjodatimeConverters_$9 *new_ComFatboyindustrialGsonjodatimeConverters_$9_init() {
  J2OBJC_NEW_IMPL(ComFatboyindustrialGsonjodatimeConverters_$9, init)
}

ComFatboyindustrialGsonjodatimeConverters_$9 *create_ComFatboyindustrialGsonjodatimeConverters_$9_init() {
  J2OBJC_CREATE_IMPL(ComFatboyindustrialGsonjodatimeConverters_$9, init)
}
