//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson-jodatime-serialisers/build/mainTranslationExtraction/com/fatboyindustrial/gsonjodatime/DateMidnightConverter.java
//

#include "DateMidnight.h"
#include "DateMidnightConverter.h"
#include "DateTime.h"
#include "DateTimeFormatter.h"
#include "ISODateTimeFormat.h"
#include "J2ObjC_source.h"
#include "JsonDeserializationContext.h"
#include "JsonElement.h"
#include "JsonPrimitive.h"
#include "JsonSerializationContext.h"
#include "java/lang/reflect/Type.h"

@implementation ComFatboyindustrialGsonjodatimeDateMidnightConverter

- (ComGoogleGsonJsonElement *)serializeWithId:(OrgJodaTimeDateMidnight *)src
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc
    withComGoogleGsonJsonSerializationContext:(id<ComGoogleGsonJsonSerializationContext>)context {
  OrgJodaTimeFormatDateTimeFormatter *fmt = OrgJodaTimeFormatISODateTimeFormat_dateTime();
  return new_ComGoogleGsonJsonPrimitive_initWithNSString_([((OrgJodaTimeFormatDateTimeFormatter *) nil_chk(fmt)) printWithOrgJodaTimeReadableInstant:src]);
}

- (OrgJodaTimeDateMidnight *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                             withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
                         withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context {
  if ([((ComGoogleGsonJsonElement *) nil_chk(json)) getAsString] == nil || [((NSString *) nil_chk([json getAsString])) isEmpty]) {
    return nil;
  }
  OrgJodaTimeFormatDateTimeFormatter *fmt = OrgJodaTimeFormatISODateTimeFormat_dateTime();
  return new_OrgJodaTimeDateMidnight_initWithId_([((OrgJodaTimeFormatDateTimeFormatter *) nil_chk(fmt)) parseDateTimeWithNSString:[json getAsString]]);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComFatboyindustrialGsonjodatimeDateMidnightConverter_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LComGoogleGsonJsonElement;", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeDateMidnight;", 0x1, 2, 3, 4, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(serializeWithId:withJavaLangReflectType:withComGoogleGsonJsonSerializationContext:);
  methods[1].selector = @selector(deserializeWithComGoogleGsonJsonElement:withJavaLangReflectType:withComGoogleGsonJsonDeserializationContext:);
  methods[2].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "serialize", "LOrgJodaTimeDateMidnight;LJavaLangReflectType;LComGoogleGsonJsonSerializationContext;", "deserialize", "LComGoogleGsonJsonElement;LJavaLangReflectType;LComGoogleGsonJsonDeserializationContext;", "LComGoogleGsonJsonParseException;", "Ljava/lang/Object;Lcom/google/gson/JsonSerializer<Lorg/joda/time/DateMidnight;>;Lcom/google/gson/JsonDeserializer<Lorg/joda/time/DateMidnight;>;" };
  static const J2ObjcClassInfo _ComFatboyindustrialGsonjodatimeDateMidnightConverter = { "DateMidnightConverter", "com.fatboyindustrial.gsonjodatime", ptrTable, methods, NULL, 7, 0x1, 3, 0, -1, -1, -1, 5, -1 };
  return &_ComFatboyindustrialGsonjodatimeDateMidnightConverter;
}

@end

void ComFatboyindustrialGsonjodatimeDateMidnightConverter_init(ComFatboyindustrialGsonjodatimeDateMidnightConverter *self) {
  NSObject_init(self);
}

ComFatboyindustrialGsonjodatimeDateMidnightConverter *new_ComFatboyindustrialGsonjodatimeDateMidnightConverter_init() {
  J2OBJC_NEW_IMPL(ComFatboyindustrialGsonjodatimeDateMidnightConverter, init)
}

ComFatboyindustrialGsonjodatimeDateMidnightConverter *create_ComFatboyindustrialGsonjodatimeDateMidnightConverter_init() {
  J2OBJC_CREATE_IMPL(ComFatboyindustrialGsonjodatimeDateMidnightConverter, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComFatboyindustrialGsonjodatimeDateMidnightConverter)
