//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson-jodatime-serialisers/build/mainTranslationExtraction/com/fatboyindustrial/gsonjodatime/DateMidnightConverter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_DateMidnightConverter")
#ifdef RESTRICT_DateMidnightConverter
#define INCLUDE_ALL_DateMidnightConverter 0
#else
#define INCLUDE_ALL_DateMidnightConverter 1
#endif
#undef RESTRICT_DateMidnightConverter

#if !defined (ComFatboyindustrialGsonjodatimeDateMidnightConverter_) && (INCLUDE_ALL_DateMidnightConverter || defined(INCLUDE_ComFatboyindustrialGsonjodatimeDateMidnightConverter))
#define ComFatboyindustrialGsonjodatimeDateMidnightConverter_

#define RESTRICT_JsonSerializer 1
#define INCLUDE_ComGoogleGsonJsonSerializer 1
#include "JsonSerializer.h"

#define RESTRICT_JsonDeserializer 1
#define INCLUDE_ComGoogleGsonJsonDeserializer 1
#include "JsonDeserializer.h"

@class ComGoogleGsonJsonElement;
@class OrgJodaTimeDateMidnight;
@protocol ComGoogleGsonJsonDeserializationContext;
@protocol ComGoogleGsonJsonSerializationContext;
@protocol JavaLangReflectType;

@interface ComFatboyindustrialGsonjodatimeDateMidnightConverter : NSObject < ComGoogleGsonJsonSerializer, ComGoogleGsonJsonDeserializer >

#pragma mark Public

- (instancetype)init;

- (OrgJodaTimeDateMidnight *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                             withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
                         withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context;

- (ComGoogleGsonJsonElement *)serializeWithId:(OrgJodaTimeDateMidnight *)src
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc
    withComGoogleGsonJsonSerializationContext:(id<ComGoogleGsonJsonSerializationContext>)context;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFatboyindustrialGsonjodatimeDateMidnightConverter)

FOUNDATION_EXPORT void ComFatboyindustrialGsonjodatimeDateMidnightConverter_init(ComFatboyindustrialGsonjodatimeDateMidnightConverter *self);

FOUNDATION_EXPORT ComFatboyindustrialGsonjodatimeDateMidnightConverter *new_ComFatboyindustrialGsonjodatimeDateMidnightConverter_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComFatboyindustrialGsonjodatimeDateMidnightConverter *create_ComFatboyindustrialGsonjodatimeDateMidnightConverter_init();

J2OBJC_TYPE_LITERAL_HEADER(ComFatboyindustrialGsonjodatimeDateMidnightConverter)

#endif

#pragma pop_macro("INCLUDE_ALL_DateMidnightConverter")
