//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson-jodatime-serialisers/build/mainTranslationExtraction/com/fatboyindustrial/gsonjodatime/DateTimeConverter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_DateTimeConverter")
#ifdef RESTRICT_DateTimeConverter
#define INCLUDE_ALL_DateTimeConverter 0
#else
#define INCLUDE_ALL_DateTimeConverter 1
#endif
#undef RESTRICT_DateTimeConverter

#if !defined (ComFatboyindustrialGsonjodatimeDateTimeConverter_) && (INCLUDE_ALL_DateTimeConverter || defined(INCLUDE_ComFatboyindustrialGsonjodatimeDateTimeConverter))
#define ComFatboyindustrialGsonjodatimeDateTimeConverter_

#define RESTRICT_JsonSerializer 1
#define INCLUDE_ComGoogleGsonJsonSerializer 1
#include "JsonSerializer.h"

#define RESTRICT_JsonDeserializer 1
#define INCLUDE_ComGoogleGsonJsonDeserializer 1
#include "JsonDeserializer.h"

@class ComGoogleGsonJsonElement;
@class OrgJodaTimeDateTime;
@protocol ComGoogleGsonJsonDeserializationContext;
@protocol ComGoogleGsonJsonSerializationContext;
@protocol JavaLangReflectType;

@interface ComFatboyindustrialGsonjodatimeDateTimeConverter : NSObject < ComGoogleGsonJsonSerializer, ComGoogleGsonJsonDeserializer >

#pragma mark Public

- (instancetype)init;

- (OrgJodaTimeDateTime *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                         withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
                     withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context;

- (ComGoogleGsonJsonElement *)serializeWithId:(OrgJodaTimeDateTime *)src
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc
    withComGoogleGsonJsonSerializationContext:(id<ComGoogleGsonJsonSerializationContext>)context;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFatboyindustrialGsonjodatimeDateTimeConverter)

FOUNDATION_EXPORT void ComFatboyindustrialGsonjodatimeDateTimeConverter_init(ComFatboyindustrialGsonjodatimeDateTimeConverter *self);

FOUNDATION_EXPORT ComFatboyindustrialGsonjodatimeDateTimeConverter *new_ComFatboyindustrialGsonjodatimeDateTimeConverter_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComFatboyindustrialGsonjodatimeDateTimeConverter *create_ComFatboyindustrialGsonjodatimeDateTimeConverter_init();

J2OBJC_TYPE_LITERAL_HEADER(ComFatboyindustrialGsonjodatimeDateTimeConverter)

#endif

#pragma pop_macro("INCLUDE_ALL_DateTimeConverter")
