//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson-jodatime-serialisers/build/mainTranslationExtraction/com/fatboyindustrial/gsonjodatime/DurationConverter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_DurationConverter")
#ifdef RESTRICT_DurationConverter
#define INCLUDE_ALL_DurationConverter 0
#else
#define INCLUDE_ALL_DurationConverter 1
#endif
#undef RESTRICT_DurationConverter

#if !defined (ComFatboyindustrialGsonjodatimeDurationConverter_) && (INCLUDE_ALL_DurationConverter || defined(INCLUDE_ComFatboyindustrialGsonjodatimeDurationConverter))
#define ComFatboyindustrialGsonjodatimeDurationConverter_

#define RESTRICT_JsonSerializer 1
#define INCLUDE_ComGoogleGsonJsonSerializer 1
#include "JsonSerializer.h"

#define RESTRICT_JsonDeserializer 1
#define INCLUDE_ComGoogleGsonJsonDeserializer 1
#include "JsonDeserializer.h"

@class ComGoogleGsonJsonElement;
@class OrgJodaTimeDuration;
@protocol ComGoogleGsonJsonDeserializationContext;
@protocol ComGoogleGsonJsonSerializationContext;
@protocol JavaLangReflectType;

@interface ComFatboyindustrialGsonjodatimeDurationConverter : NSObject < ComGoogleGsonJsonSerializer, ComGoogleGsonJsonDeserializer >

#pragma mark Public

- (instancetype)init;

- (OrgJodaTimeDuration *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                         withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
                     withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context;

- (ComGoogleGsonJsonElement *)serializeWithId:(OrgJodaTimeDuration *)src
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc
    withComGoogleGsonJsonSerializationContext:(id<ComGoogleGsonJsonSerializationContext>)context;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFatboyindustrialGsonjodatimeDurationConverter)

FOUNDATION_EXPORT void ComFatboyindustrialGsonjodatimeDurationConverter_init(ComFatboyindustrialGsonjodatimeDurationConverter *self);

FOUNDATION_EXPORT ComFatboyindustrialGsonjodatimeDurationConverter *new_ComFatboyindustrialGsonjodatimeDurationConverter_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComFatboyindustrialGsonjodatimeDurationConverter *create_ComFatboyindustrialGsonjodatimeDurationConverter_init();

J2OBJC_TYPE_LITERAL_HEADER(ComFatboyindustrialGsonjodatimeDurationConverter)

#endif

#pragma pop_macro("INCLUDE_ALL_DurationConverter")
