//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson-jodatime-serialisers/build/mainTranslationExtraction/com/fatboyindustrial/gsonjodatime/InstantConverter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_InstantConverter")
#ifdef RESTRICT_InstantConverter
#define INCLUDE_ALL_InstantConverter 0
#else
#define INCLUDE_ALL_InstantConverter 1
#endif
#undef RESTRICT_InstantConverter

#if !defined (ComFatboyindustrialGsonjodatimeInstantConverter_) && (INCLUDE_ALL_InstantConverter || defined(INCLUDE_ComFatboyindustrialGsonjodatimeInstantConverter))
#define ComFatboyindustrialGsonjodatimeInstantConverter_

#define RESTRICT_JsonSerializer 1
#define INCLUDE_ComGoogleGsonJsonSerializer 1
#include "JsonSerializer.h"

#define RESTRICT_JsonDeserializer 1
#define INCLUDE_ComGoogleGsonJsonDeserializer 1
#include "JsonDeserializer.h"

@class ComGoogleGsonJsonElement;
@class OrgJodaTimeInstant;
@protocol ComGoogleGsonJsonDeserializationContext;
@protocol ComGoogleGsonJsonSerializationContext;
@protocol JavaLangReflectType;

@interface ComFatboyindustrialGsonjodatimeInstantConverter : NSObject < ComGoogleGsonJsonSerializer, ComGoogleGsonJsonDeserializer >

#pragma mark Public

- (instancetype)init;

- (OrgJodaTimeInstant *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                        withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
                    withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context;

- (ComGoogleGsonJsonElement *)serializeWithId:(OrgJodaTimeInstant *)src
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc
    withComGoogleGsonJsonSerializationContext:(id<ComGoogleGsonJsonSerializationContext>)context;

@end

J2OBJC_STATIC_INIT(ComFatboyindustrialGsonjodatimeInstantConverter)

FOUNDATION_EXPORT void ComFatboyindustrialGsonjodatimeInstantConverter_init(ComFatboyindustrialGsonjodatimeInstantConverter *self);

FOUNDATION_EXPORT ComFatboyindustrialGsonjodatimeInstantConverter *new_ComFatboyindustrialGsonjodatimeInstantConverter_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComFatboyindustrialGsonjodatimeInstantConverter *create_ComFatboyindustrialGsonjodatimeInstantConverter_init();

J2OBJC_TYPE_LITERAL_HEADER(ComFatboyindustrialGsonjodatimeInstantConverter)

#endif

#pragma pop_macro("INCLUDE_ALL_InstantConverter")
