//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson-jodatime-serialisers/build/mainTranslationExtraction/com/fatboyindustrial/gsonjodatime/InstantConverter.java
//

#include "DateTimeFormat.h"
#include "DateTimeFormatter.h"
#include "Instant.h"
#include "InstantConverter.h"
#include "J2ObjC_source.h"
#include "JsonDeserializationContext.h"
#include "JsonElement.h"
#include "JsonPrimitive.h"
#include "JsonSerializationContext.h"
#include "java/lang/reflect/Type.h"

inline OrgJodaTimeFormatDateTimeFormatter *ComFatboyindustrialGsonjodatimeInstantConverter_get_fmt();
static OrgJodaTimeFormatDateTimeFormatter *ComFatboyindustrialGsonjodatimeInstantConverter_fmt;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComFatboyindustrialGsonjodatimeInstantConverter, fmt, OrgJodaTimeFormatDateTimeFormatter *)

J2OBJC_INITIALIZED_DEFN(ComFatboyindustrialGsonjodatimeInstantConverter)

@implementation ComFatboyindustrialGsonjodatimeInstantConverter

- (ComGoogleGsonJsonElement *)serializeWithId:(OrgJodaTimeInstant *)src
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc
    withComGoogleGsonJsonSerializationContext:(id<ComGoogleGsonJsonSerializationContext>)context {
  return new_ComGoogleGsonJsonPrimitive_initWithNSString_([((OrgJodaTimeFormatDateTimeFormatter *) nil_chk(ComFatboyindustrialGsonjodatimeInstantConverter_fmt)) printWithOrgJodaTimeReadableInstant:src]);
}

- (OrgJodaTimeInstant *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                        withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
                    withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context {
  if ([((ComGoogleGsonJsonElement *) nil_chk(json)) getAsString] == nil || [((NSString *) nil_chk([json getAsString])) isEmpty]) {
    return nil;
  }
  return OrgJodaTimeInstant_parseWithNSString_withOrgJodaTimeFormatDateTimeFormatter_([json getAsString], ComFatboyindustrialGsonjodatimeInstantConverter_fmt);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComFatboyindustrialGsonjodatimeInstantConverter_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LComGoogleGsonJsonElement;", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeInstant;", 0x1, 2, 3, 4, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(serializeWithId:withJavaLangReflectType:withComGoogleGsonJsonSerializationContext:);
  methods[1].selector = @selector(deserializeWithComGoogleGsonJsonElement:withJavaLangReflectType:withComGoogleGsonJsonDeserializationContext:);
  methods[2].selector = @selector(init);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "fmt", "LOrgJodaTimeFormatDateTimeFormatter;", .constantValue.asLong = 0, 0x1a, -1, 5, -1, -1 },
  };
  static const void *ptrTable[] = { "serialize", "LOrgJodaTimeInstant;LJavaLangReflectType;LComGoogleGsonJsonSerializationContext;", "deserialize", "LComGoogleGsonJsonElement;LJavaLangReflectType;LComGoogleGsonJsonDeserializationContext;", "LComGoogleGsonJsonParseException;", &ComFatboyindustrialGsonjodatimeInstantConverter_fmt, "Ljava/lang/Object;Lcom/google/gson/JsonSerializer<Lorg/joda/time/Instant;>;Lcom/google/gson/JsonDeserializer<Lorg/joda/time/Instant;>;" };
  static const J2ObjcClassInfo _ComFatboyindustrialGsonjodatimeInstantConverter = { "InstantConverter", "com.fatboyindustrial.gsonjodatime", ptrTable, methods, fields, 7, 0x1, 3, 1, -1, -1, -1, 6, -1 };
  return &_ComFatboyindustrialGsonjodatimeInstantConverter;
}

+ (void)initialize {
  if (self == [ComFatboyindustrialGsonjodatimeInstantConverter class]) {
    ComFatboyindustrialGsonjodatimeInstantConverter_fmt = [((OrgJodaTimeFormatDateTimeFormatter *) nil_chk(OrgJodaTimeFormatDateTimeFormat_forPatternWithNSString_(@"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"))) withZoneUTC];
    J2OBJC_SET_INITIALIZED(ComFatboyindustrialGsonjodatimeInstantConverter)
  }
}

@end

void ComFatboyindustrialGsonjodatimeInstantConverter_init(ComFatboyindustrialGsonjodatimeInstantConverter *self) {
  NSObject_init(self);
}

ComFatboyindustrialGsonjodatimeInstantConverter *new_ComFatboyindustrialGsonjodatimeInstantConverter_init() {
  J2OBJC_NEW_IMPL(ComFatboyindustrialGsonjodatimeInstantConverter, init)
}

ComFatboyindustrialGsonjodatimeInstantConverter *create_ComFatboyindustrialGsonjodatimeInstantConverter_init() {
  J2OBJC_CREATE_IMPL(ComFatboyindustrialGsonjodatimeInstantConverter, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComFatboyindustrialGsonjodatimeInstantConverter)
