//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson-jodatime-serialisers/build/mainTranslationExtraction/com/fatboyindustrial/gsonjodatime/IntervalConverter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_IntervalConverter")
#ifdef RESTRICT_IntervalConverter
#define INCLUDE_ALL_IntervalConverter 0
#else
#define INCLUDE_ALL_IntervalConverter 1
#endif
#undef RESTRICT_IntervalConverter

#if !defined (ComFatboyindustrialGsonjodatimeIntervalConverter_) && (INCLUDE_ALL_IntervalConverter || defined(INCLUDE_ComFatboyindustrialGsonjodatimeIntervalConverter))
#define ComFatboyindustrialGsonjodatimeIntervalConverter_

#define RESTRICT_JsonSerializer 1
#define INCLUDE_ComGoogleGsonJsonSerializer 1
#include "JsonSerializer.h"

#define RESTRICT_JsonDeserializer 1
#define INCLUDE_ComGoogleGsonJsonDeserializer 1
#include "JsonDeserializer.h"

@class ComGoogleGsonJsonElement;
@class OrgJodaTimeInterval;
@protocol ComGoogleGsonJsonDeserializationContext;
@protocol ComGoogleGsonJsonSerializationContext;
@protocol JavaLangReflectType;

@interface ComFatboyindustrialGsonjodatimeIntervalConverter : NSObject < ComGoogleGsonJsonSerializer, ComGoogleGsonJsonDeserializer >

#pragma mark Public

- (instancetype)init;

- (OrgJodaTimeInterval *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                         withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
                     withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context;

- (ComGoogleGsonJsonElement *)serializeWithId:(OrgJodaTimeInterval *)src
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc
    withComGoogleGsonJsonSerializationContext:(id<ComGoogleGsonJsonSerializationContext>)context;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFatboyindustrialGsonjodatimeIntervalConverter)

FOUNDATION_EXPORT void ComFatboyindustrialGsonjodatimeIntervalConverter_init(ComFatboyindustrialGsonjodatimeIntervalConverter *self);

FOUNDATION_EXPORT ComFatboyindustrialGsonjodatimeIntervalConverter *new_ComFatboyindustrialGsonjodatimeIntervalConverter_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComFatboyindustrialGsonjodatimeIntervalConverter *create_ComFatboyindustrialGsonjodatimeIntervalConverter_init();

J2OBJC_TYPE_LITERAL_HEADER(ComFatboyindustrialGsonjodatimeIntervalConverter)

#endif

#pragma pop_macro("INCLUDE_ALL_IntervalConverter")
