//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson-jodatime-serialisers/build/mainTranslationExtraction/com/fatboyindustrial/gsonjodatime/LocalTimeConverter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_LocalTimeConverter")
#ifdef RESTRICT_LocalTimeConverter
#define INCLUDE_ALL_LocalTimeConverter 0
#else
#define INCLUDE_ALL_LocalTimeConverter 1
#endif
#undef RESTRICT_LocalTimeConverter

#if !defined (ComFatboyindustrialGsonjodatimeLocalTimeConverter_) && (INCLUDE_ALL_LocalTimeConverter || defined(INCLUDE_ComFatboyindustrialGsonjodatimeLocalTimeConverter))
#define ComFatboyindustrialGsonjodatimeLocalTimeConverter_

#define RESTRICT_JsonSerializer 1
#define INCLUDE_ComGoogleGsonJsonSerializer 1
#include "JsonSerializer.h"

#define RESTRICT_JsonDeserializer 1
#define INCLUDE_ComGoogleGsonJsonDeserializer 1
#include "JsonDeserializer.h"

@class ComGoogleGsonJsonElement;
@class OrgJodaTimeLocalTime;
@protocol ComGoogleGsonJsonDeserializationContext;
@protocol ComGoogleGsonJsonSerializationContext;
@protocol JavaLangReflectType;

@interface ComFatboyindustrialGsonjodatimeLocalTimeConverter : NSObject < ComGoogleGsonJsonSerializer, ComGoogleGsonJsonDeserializer >

#pragma mark Public

- (instancetype)init;

- (OrgJodaTimeLocalTime *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                          withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
                      withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context;

- (ComGoogleGsonJsonElement *)serializeWithId:(OrgJodaTimeLocalTime *)src
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc
    withComGoogleGsonJsonSerializationContext:(id<ComGoogleGsonJsonSerializationContext>)context;

@end

J2OBJC_STATIC_INIT(ComFatboyindustrialGsonjodatimeLocalTimeConverter)

FOUNDATION_EXPORT void ComFatboyindustrialGsonjodatimeLocalTimeConverter_init(ComFatboyindustrialGsonjodatimeLocalTimeConverter *self);

FOUNDATION_EXPORT ComFatboyindustrialGsonjodatimeLocalTimeConverter *new_ComFatboyindustrialGsonjodatimeLocalTimeConverter_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComFatboyindustrialGsonjodatimeLocalTimeConverter *create_ComFatboyindustrialGsonjodatimeLocalTimeConverter_init();

J2OBJC_TYPE_LITERAL_HEADER(ComFatboyindustrialGsonjodatimeLocalTimeConverter)

#endif

#pragma pop_macro("INCLUDE_ALL_LocalTimeConverter")
