//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson-jodatime-serialisers/build/mainTranslationExtraction/com/fatboyindustrial/gsonjodatime/LocalDateTimeConverter.java
//

#include "DateTimeFormat.h"
#include "DateTimeFormatter.h"
#include "J2ObjC_source.h"
#include "JsonDeserializationContext.h"
#include "JsonElement.h"
#include "JsonPrimitive.h"
#include "JsonSerializationContext.h"
#include "LocalDateTime.h"
#include "LocalDateTimeConverter.h"
#include "java/lang/reflect/Type.h"

inline NSString *ComFatboyindustrialGsonjodatimeLocalDateTimeConverter_get_PATTERN();
static NSString *ComFatboyindustrialGsonjodatimeLocalDateTimeConverter_PATTERN = @"yyyy-MM-dd'T'HH:mm:ss.SSS";
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComFatboyindustrialGsonjodatimeLocalDateTimeConverter, PATTERN, NSString *)

@implementation ComFatboyindustrialGsonjodatimeLocalDateTimeConverter

- (ComGoogleGsonJsonElement *)serializeWithId:(OrgJodaTimeLocalDateTime *)src
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc
    withComGoogleGsonJsonSerializationContext:(id<ComGoogleGsonJsonSerializationContext>)context {
  OrgJodaTimeFormatDateTimeFormatter *fmt = OrgJodaTimeFormatDateTimeFormat_forPatternWithNSString_(ComFatboyindustrialGsonjodatimeLocalDateTimeConverter_PATTERN);
  return new_ComGoogleGsonJsonPrimitive_initWithNSString_([((OrgJodaTimeFormatDateTimeFormatter *) nil_chk(fmt)) printWithOrgJodaTimeReadablePartial:src]);
}

- (OrgJodaTimeLocalDateTime *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                              withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
                          withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context {
  if ([((ComGoogleGsonJsonElement *) nil_chk(json)) getAsString] == nil || [((NSString *) nil_chk([json getAsString])) isEmpty]) {
    return nil;
  }
  OrgJodaTimeFormatDateTimeFormatter *fmt = OrgJodaTimeFormatDateTimeFormat_forPatternWithNSString_(ComFatboyindustrialGsonjodatimeLocalDateTimeConverter_PATTERN);
  return [((OrgJodaTimeFormatDateTimeFormatter *) nil_chk(fmt)) parseLocalDateTimeWithNSString:[json getAsString]];
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComFatboyindustrialGsonjodatimeLocalDateTimeConverter_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LComGoogleGsonJsonElement;", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimeLocalDateTime;", 0x1, 2, 3, 4, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(serializeWithId:withJavaLangReflectType:withComGoogleGsonJsonSerializationContext:);
  methods[1].selector = @selector(deserializeWithComGoogleGsonJsonElement:withJavaLangReflectType:withComGoogleGsonJsonDeserializationContext:);
  methods[2].selector = @selector(init);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "PATTERN", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 5, -1, -1 },
  };
  static const void *ptrTable[] = { "serialize", "LOrgJodaTimeLocalDateTime;LJavaLangReflectType;LComGoogleGsonJsonSerializationContext;", "deserialize", "LComGoogleGsonJsonElement;LJavaLangReflectType;LComGoogleGsonJsonDeserializationContext;", "LComGoogleGsonJsonParseException;", &ComFatboyindustrialGsonjodatimeLocalDateTimeConverter_PATTERN, "Ljava/lang/Object;Lcom/google/gson/JsonSerializer<Lorg/joda/time/LocalDateTime;>;Lcom/google/gson/JsonDeserializer<Lorg/joda/time/LocalDateTime;>;" };
  static const J2ObjcClassInfo _ComFatboyindustrialGsonjodatimeLocalDateTimeConverter = { "LocalDateTimeConverter", "com.fatboyindustrial.gsonjodatime", ptrTable, methods, fields, 7, 0x1, 3, 1, -1, -1, -1, 6, -1 };
  return &_ComFatboyindustrialGsonjodatimeLocalDateTimeConverter;
}

@end

void ComFatboyindustrialGsonjodatimeLocalDateTimeConverter_init(ComFatboyindustrialGsonjodatimeLocalDateTimeConverter *self) {
  NSObject_init(self);
}

ComFatboyindustrialGsonjodatimeLocalDateTimeConverter *new_ComFatboyindustrialGsonjodatimeLocalDateTimeConverter_init() {
  J2OBJC_NEW_IMPL(ComFatboyindustrialGsonjodatimeLocalDateTimeConverter, init)
}

ComFatboyindustrialGsonjodatimeLocalDateTimeConverter *create_ComFatboyindustrialGsonjodatimeLocalDateTimeConverter_init() {
  J2OBJC_CREATE_IMPL(ComFatboyindustrialGsonjodatimeLocalDateTimeConverter, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComFatboyindustrialGsonjodatimeLocalDateTimeConverter)
