//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson-jodatime-serialisers/build/mainTranslationExtraction/com/fatboyindustrial/gsonjodatime/package-info.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Package_info")
#ifdef RESTRICT_Package_info
#define INCLUDE_ALL_Package_info 0
#else
#define INCLUDE_ALL_Package_info 1
#endif
#undef RESTRICT_Package_info

#pragma pop_macro("INCLUDE_ALL_Package_info")
