//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson-jodatime-serialisers/build/mainTranslationExtraction/com/fatboyindustrial/gsonjodatime/PeriodConverter.java
//

#include "ISOPeriodFormat.h"
#include "J2ObjC_source.h"
#include "JsonDeserializationContext.h"
#include "JsonElement.h"
#include "JsonPrimitive.h"
#include "JsonSerializationContext.h"
#include "Period.h"
#include "PeriodConverter.h"
#include "PeriodFormatter.h"
#include "java/lang/reflect/Type.h"

@implementation ComFatboyindustrialGsonjodatimePeriodConverter

- (ComGoogleGsonJsonElement *)serializeWithId:(OrgJodaTimePeriod *)src
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc
    withComGoogleGsonJsonSerializationContext:(id<ComGoogleGsonJsonSerializationContext>)context {
  OrgJodaTimeFormatPeriodFormatter *fmt = OrgJodaTimeFormatISOPeriodFormat_standard();
  return new_ComGoogleGsonJsonPrimitive_initWithNSString_([((OrgJodaTimeFormatPeriodFormatter *) nil_chk(fmt)) printWithOrgJodaTimeReadablePeriod:src]);
}

- (OrgJodaTimePeriod *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                       withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
                   withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context {
  if ([((ComGoogleGsonJsonElement *) nil_chk(json)) getAsString] == nil || [((NSString *) nil_chk([json getAsString])) isEmpty]) {
    return nil;
  }
  OrgJodaTimeFormatPeriodFormatter *fmt = OrgJodaTimeFormatISOPeriodFormat_standard();
  return [((OrgJodaTimeFormatPeriodFormatter *) nil_chk(fmt)) parsePeriodWithNSString:[json getAsString]];
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComFatboyindustrialGsonjodatimePeriodConverter_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LComGoogleGsonJsonElement;", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "LOrgJodaTimePeriod;", 0x1, 2, 3, 4, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(serializeWithId:withJavaLangReflectType:withComGoogleGsonJsonSerializationContext:);
  methods[1].selector = @selector(deserializeWithComGoogleGsonJsonElement:withJavaLangReflectType:withComGoogleGsonJsonDeserializationContext:);
  methods[2].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "serialize", "LOrgJodaTimePeriod;LJavaLangReflectType;LComGoogleGsonJsonSerializationContext;", "deserialize", "LComGoogleGsonJsonElement;LJavaLangReflectType;LComGoogleGsonJsonDeserializationContext;", "LComGoogleGsonJsonParseException;", "Ljava/lang/Object;Lcom/google/gson/JsonSerializer<Lorg/joda/time/Period;>;Lcom/google/gson/JsonDeserializer<Lorg/joda/time/Period;>;" };
  static const J2ObjcClassInfo _ComFatboyindustrialGsonjodatimePeriodConverter = { "PeriodConverter", "com.fatboyindustrial.gsonjodatime", ptrTable, methods, NULL, 7, 0x1, 3, 0, -1, -1, -1, 5, -1 };
  return &_ComFatboyindustrialGsonjodatimePeriodConverter;
}

@end

void ComFatboyindustrialGsonjodatimePeriodConverter_init(ComFatboyindustrialGsonjodatimePeriodConverter *self) {
  NSObject_init(self);
}

ComFatboyindustrialGsonjodatimePeriodConverter *new_ComFatboyindustrialGsonjodatimePeriodConverter_init() {
  J2OBJC_NEW_IMPL(ComFatboyindustrialGsonjodatimePeriodConverter, init)
}

ComFatboyindustrialGsonjodatimePeriodConverter *create_ComFatboyindustrialGsonjodatimePeriodConverter_init() {
  J2OBJC_CREATE_IMPL(ComFatboyindustrialGsonjodatimePeriodConverter, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComFatboyindustrialGsonjodatimePeriodConverter)
