//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/eric/repos/360-j2objc/gson-jodatime-serialisers/build/mainTranslationExtraction/com/fatboyindustrial/gsonjodatime/PeriodConverter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PeriodConverter")
#ifdef RESTRICT_PeriodConverter
#define INCLUDE_ALL_PeriodConverter 0
#else
#define INCLUDE_ALL_PeriodConverter 1
#endif
#undef RESTRICT_PeriodConverter

#if !defined (ComFatboyindustrialGsonjodatimePeriodConverter_) && (INCLUDE_ALL_PeriodConverter || defined(INCLUDE_ComFatboyindustrialGsonjodatimePeriodConverter))
#define ComFatboyindustrialGsonjodatimePeriodConverter_

#define RESTRICT_JsonSerializer 1
#define INCLUDE_ComGoogleGsonJsonSerializer 1
#include "JsonSerializer.h"

#define RESTRICT_JsonDeserializer 1
#define INCLUDE_ComGoogleGsonJsonDeserializer 1
#include "JsonDeserializer.h"

@class ComGoogleGsonJsonElement;
@class OrgJodaTimePeriod;
@protocol ComGoogleGsonJsonDeserializationContext;
@protocol ComGoogleGsonJsonSerializationContext;
@protocol JavaLangReflectType;

@interface ComFatboyindustrialGsonjodatimePeriodConverter : NSObject < ComGoogleGsonJsonSerializer, ComGoogleGsonJsonDeserializer >

#pragma mark Public

- (instancetype)init;

- (OrgJodaTimePeriod *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                       withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
                   withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context;

- (ComGoogleGsonJsonElement *)serializeWithId:(OrgJodaTimePeriod *)src
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc
    withComGoogleGsonJsonSerializationContext:(id<ComGoogleGsonJsonSerializationContext>)context;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFatboyindustrialGsonjodatimePeriodConverter)

FOUNDATION_EXPORT void ComFatboyindustrialGsonjodatimePeriodConverter_init(ComFatboyindustrialGsonjodatimePeriodConverter *self);

FOUNDATION_EXPORT ComFatboyindustrialGsonjodatimePeriodConverter *new_ComFatboyindustrialGsonjodatimePeriodConverter_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComFatboyindustrialGsonjodatimePeriodConverter *create_ComFatboyindustrialGsonjodatimePeriodConverter_init();

J2OBJC_TYPE_LITERAL_HEADER(ComFatboyindustrialGsonjodatimePeriodConverter)

#endif

#pragma pop_macro("INCLUDE_ALL_PeriodConverter")
